name: Github Actions CI

on:
  pull_request:
  push:
    branches:
      - master
      - develop
      - githubactions*
      - feature/**
      - fix/**
      - pr/**


env:
    B2_VARIANT: variant=release,debug

jobs:
  posix:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "TOOLSET=gcc-4.4 CXXSTD=98,0x Job 0"
            buildtype: "boost"
            packages: "g++-4.4"
            packages_to_remove: ""
            os: "ubuntu-16.04"
            cxx: "g++"
            sources: ""
            llvm_os: ""
            llvm_ver: ""
            toolset: "gcc-4.4"
            cxxstd: "98,0x"
            drone_job_uuid: "b6589fc6ab"
          - name: "TOOLSET=gcc-4.6 CXXSTD=03,0x Job 1"
            buildtype: "boost"
            packages: "g++-4.6"
            packages_to_remove: ""
            os: "ubuntu-16.04"
            cxx: "g++"
            sources: ""
            llvm_os: ""
            llvm_ver: ""
            toolset: "gcc-4.6"
            cxxstd: "03,0x"
            drone_job_uuid: "356a192b79"
          - name: "TOOLSET=gcc-4.8 CXXSTD=03,11 Job 2"
            buildtype: "boost"
            packages: "g++-4.8"
            packages_to_remove: ""
            os: "ubuntu-16.04"
            cxx: "g++"
            sources: ""
            llvm_os: ""
            llvm_ver: ""
            toolset: "gcc-4.8"
            cxxstd: "03,11"
            drone_job_uuid: "da4b9237ba"
          - name: "TOOLSET=gcc-5 CXXSTD=03,11 Job 3"
            buildtype: "boost"
            packages: "g++-5"
            packages_to_remove: ""
            os: "ubuntu-16.04"
            cxx: "g++"
            sources: ""
            llvm_os: ""
            llvm_ver: ""
            toolset: "gcc-5"
            cxxstd: "03,11"
            drone_job_uuid: "77de68daec"
          - name: "TOOLSET=gcc-6 CXXSTD=03,11,14 Job 4"
            buildtype: "boost"
            packages: "g++-6"
            packages_to_remove: ""
            os: "ubuntu-16.04"
            cxx: "g++"
            sources: ""
            llvm_os: ""
            llvm_ver: ""
            toolset: "gcc-6"
            cxxstd: "03,11,14"
            drone_job_uuid: "1b64538924"
          - name: "TOOLSET=gcc-7 CXXSTD=03,11,14,17 Job 5"
            buildtype: "boost"
            packages: "g++-7"
            packages_to_remove: ""
            os: "ubuntu-16.04"
            cxx: "g++"
            sources: ""
            llvm_os: ""
            llvm_ver: ""
            toolset: "gcc-7"
            cxxstd: "03,11,14,17"
            drone_job_uuid: "ac3478d69a"
          - name: "TOOLSET=gcc-8 CXXSTD=03,11,14,17,2a Job 6"
            buildtype: "boost"
            packages: "g++-8"
            packages_to_remove: ""
            os: "ubuntu-16.04"
            cxx: "g++"
            sources: ""
            llvm_os: ""
            llvm_ver: ""
            toolset: "gcc-8"
            cxxstd: "03,11,14,17,2a"
            drone_job_uuid: "c1dfd96eea"
          - name: "TOOLSET=clang-3.4 CXXSTD=03,11 Job 7"
            buildtype: "boost"
            packages: "clang-3.4"
            packages_to_remove: ""
            os: "ubuntu-16.04"
            cxx: "g++"
            sources: ""
            llvm_os: "trusty"
            llvm_ver: "3.4"
            toolset: "clang-3.4"
            cxxstd: "03,11"
            drone_job_uuid: "902ba3cda1"
          - name: "TOOLSET=clang-3.8 CXXSTD=03,11,14 Job 8"
            buildtype: "boost"
            packages: "clang-3.8 libstdc++-6-dev"
            packages_to_remove: ""
            os: "ubuntu-16.04"
            cxx: "g++"
            sources: ""
            llvm_os: "trusty"
            llvm_ver: "3.8"
            toolset: "clang-3.8"
            cxxstd: "03,11,14"
            drone_job_uuid: "fe5dbbcea5"
          - name: "TOOLSET=clang-4.0 CXXSTD=03,11,14 Job 9"
            buildtype: "boost"
            packages: "clang-4.0 libstdc++-6-dev"
            packages_to_remove: ""
            os: "ubuntu-16.04"
            cxx: "g++"
            sources: ""
            llvm_os: "trusty"
            llvm_ver: "4.0"
            toolset: "clang-4.0"
            cxxstd: "03,11,14"
            drone_job_uuid: "0ade7c2cf9"
          - name: "TOOLSET=clang-5.0 CXXSTD=03,11,14,17 Job 10"
            buildtype: "boost"
            packages: "clang-5.0 libstdc++-7-dev"
            packages_to_remove: ""
            os: "ubuntu-16.04"
            cxx: "g++"
            sources: ""
            llvm_os: "trusty"
            llvm_ver: "5.0"
            toolset: "clang-5.0"
            cxxstd: "03,11,14,17"
            drone_job_uuid: "b1d5781111"
          - name: "TOOLSET=clang-6.0 CXXSTD=03,11,14,17,2a Job 11"
            buildtype: "boost"
            packages: "clang-6.0 libc++-dev libstdc++-8-dev valgrind"
            packages_to_remove: ""
            os: "ubuntu-16.04"
            cxx: "g++"
            sources: ""
            llvm_os: "trusty"
            llvm_ver: "6.0"
            toolset: "clang-6.0"
            cxxstd: "03,11,14,17,2a"
            drone_job_uuid: "17ba079149"
          - name: "TOOLSET=clang-6.0 CXXSTD=03,11,14,17,2a Job 12"
            buildtype: "boost"
            packages: "clang-6.0 libc++-dev libstdc++-8-dev valgrind"
            packages_to_remove: ""
            os: "ubuntu-16.04"
            cxx: "g++"
            sources: ""
            llvm_os: "trusty"
            llvm_ver: "6.0"
            toolset: "clang-6.0"
            cxxstd: "03,11,14,17,2a"
            cxxflags: "-stdlib=libc++"
            drone_job_uuid: "7b52009b64"
          - name: "COMMENT=codecov.io TOOLSET=gcc-7 DEFINES=def Job 13"
            buildtype: "6d5a3a255d-bbb3de2b00"
            packages: "g++-7"
            packages_to_remove: ""
            os: "ubuntu-16.04"
            cxx: "g++"
            sources: ""
            llvm_os: ""
            llvm_ver: ""
            comment: "codecov.io"
            toolset: "gcc-7"
            defines: "define=BOOST_NO_STRESS_TEST=1"
            drone_job_uuid: "bd307a3ec3"
          - name: "COMMENT=cppcheck Job 14"
            buildtype: "6d5a3a255d-ed45733e6c"
            packages: "binutils-gold gdb libc6-dbg"
            packages_to_remove: ""
            os: "ubuntu-16.04"
            cxx: "g++"
            sources: ""
            llvm_os: ""
            llvm_ver: ""
            comment: "cppcheck"
            drone_job_uuid: "fa35e19212"
          - name: "COMMENT=ubsan B2_VARIANT=variant=debug TOOLSE Job 15"
            buildtype: "boost"
            packages: "g++-8"
            packages_to_remove: ""
            os: "ubuntu-16.04"
            cxx: "g++"
            sources: ""
            llvm_os: ""
            llvm_ver: ""
            comment: "ubsan"
            b2_variant: "variant=debug"
            toolset: "gcc-8"
            cxxstd: "03,11,14,17,2a"
            defines: "define=BOOST_NO_STRESS_TEST=1"
            cxxflags: "cxxflags=-fno-omit-frame-pointer cxxflags=-fsanitize=undefined cxxflags=-fno-sanitize-recover=undefined"
            linkflags: "linkflags=-fsanitize=undefined linkflags=-fno-sanitize-recover=undefined linkflags=-fuse-ld=gold"
            ubsan_options: "print_stacktrace=1"
            drone_job_uuid: "f1abd67035"
          - name: "COMMENT=valgrind TOOLSET=clang-6.0 CXXSTD=03, Job 16"
            buildtype: "boost"
            packages: "clang-6.0 libc++-dev libstdc++-8-dev valgrind"
            packages_to_remove: ""
            os: "ubuntu-16.04"
            cxx: "g++"
            sources: ""
            llvm_os: "trusty"
            llvm_ver: "6.0"
            comment: "valgrind"
            toolset: "clang-6.0"
            cxxstd: "03,11,14,17,2a"
            defines: "define=BOOST_NO_STRESS_TEST=1"
            b2_variant: "variant=debug"
            testflags: "testing.launcher=valgrind"
            valgrind_opts: "--error-exitcode=1"
            drone_job_uuid: "1574bddb75"
          - name: "COMMENT=Coverity Scan TOOLSET=gcc-7 Job 17"
            buildtype: "6d5a3a255d-cce9827eb5"
            packages: "g++-7"
            packages_to_remove: ""
            os: "ubuntu-16.04"
            cxx: "g++"
            sources: ""
            llvm_os: ""
            llvm_ver: ""
            comment: "Coverity Scan"
            toolset: "gcc-7"
            drone_job_uuid: "0716d9708d"

    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v2
      - name: Check if running in container
        if: matrix.container != ''
        run: echo "GHA_CONTAINER=${{ matrix.container }}" >> $GITHUB_ENV
      - name: boost
        #if: ${{ matrix.buildtype }} == boost
        if: matrix.buildtype == 'boost'
        shell: bash
        env:
          TRAVIS_BRANCH: ${{ github.base_ref }}
          CXX: ${{ matrix.cxx }}
          SOURCES: ${{ matrix.sources }}
          LLVM_OS: ${{ matrix.llvm_os }}
          LLVM_VER: ${{ matrix.llvm_ver }}
          PACKAGES: ${{ matrix.packages }}
          PACKAGES_TO_REMOVE: ${{ matrix.packages_to_remove }}
          TOOLSET: ${{ matrix.toolset }}
          CXXSTD: ${{ matrix.cxxstd }}
          DRONE_JOB_UUID: ${{ matrix.drone_job_uuid }}
          CXXFLAGS: ${{ matrix.cxxflags }}
          COMMENT: ${{ matrix.comment }}
          DEFINES: ${{ matrix.defines }}
          B2_VARIANT: ${{ matrix.b2_variant }}
          LINKFLAGS: ${{ matrix.linkflags }}
          UBSAN_OPTIONS: ${{ matrix.ubsan_options }}
          TESTFLAGS: ${{ matrix.testflags }}
          VALGRIND_OPTS: ${{ matrix.valgrind_opts }}
        run: |
          echo '==================================> SETUP'
          BOOST_CI_ORG=boostorg BOOST_CI_BRANCH=master && wget https://github.com/$BOOST_CI_ORG/boost-ci/archive/$BOOST_CI_BRANCH.tar.gz && tar -xvf $BOOST_CI_BRANCH.tar.gz && mkdir -p .github &&  mv boost-ci-$BOOST_CI_BRANCH .github/boost-ci
          echo '==================================> PACKAGES'
          set -ex
          echo "Before package removal or install"
          whoami
          dpkg -l
          echo "Checking /usr/local"
          ls -al /usr/local
          echo "Checking clang"
          which clang++ || true
          clang++ --version || true
          ls -al /etc/alternatives
          ls -al /usr/bin/c*
          echo "about to run sudo apt-get purge -y $PACKAGES_TO_REMOVE"
          if [ -n "$PACKAGES_TO_REMOVE" ]; then sudo apt-get purge -y $PACKAGES_TO_REMOVE; fi
          echo "about to run linux-cxx-install.sh"
          ./.github/boost-ci/ci/drone/linux-cxx-install.sh
          echo "After package removal and install"
          dpkg -l
          echo "Checking /usr/local"
          ls -al /usr/local
          echo "Checking clang"
          which clang++ || true
          clang++ --version || true
          ls -al /etc/alternatives
          ls -al /usr/bin/c*
          echo '==================================> INSTALL AND COMPILE'
          . .github/scripts/boost.sh
       
      - name: 6d5a3a255d-bbb3de2b00
        #if: ${{ matrix.buildtype }} == 6d5a3a255d-bbb3de2b00
        if: matrix.buildtype == '6d5a3a255d-bbb3de2b00'
        shell: bash
        env:
          TRAVIS_BRANCH: ${{ github.base_ref }}
          CXX: ${{ matrix.cxx }}
          SOURCES: ${{ matrix.sources }}
          LLVM_OS: ${{ matrix.llvm_os }}
          LLVM_VER: ${{ matrix.llvm_ver }}
          PACKAGES: ${{ matrix.packages }}
          PACKAGES_TO_REMOVE: ${{ matrix.packages_to_remove }}
          TOOLSET: ${{ matrix.toolset }}
          CXXSTD: ${{ matrix.cxxstd }}
          DRONE_JOB_UUID: ${{ matrix.drone_job_uuid }}
          CXXFLAGS: ${{ matrix.cxxflags }}
          COMMENT: ${{ matrix.comment }}
          DEFINES: ${{ matrix.defines }}
          B2_VARIANT: ${{ matrix.b2_variant }}
          LINKFLAGS: ${{ matrix.linkflags }}
          UBSAN_OPTIONS: ${{ matrix.ubsan_options }}
          TESTFLAGS: ${{ matrix.testflags }}
          VALGRIND_OPTS: ${{ matrix.valgrind_opts }}
        run: |
          echo '==================================> SETUP'
          BOOST_CI_ORG=boostorg BOOST_CI_BRANCH=master && wget https://github.com/$BOOST_CI_ORG/boost-ci/archive/$BOOST_CI_BRANCH.tar.gz && tar -xvf $BOOST_CI_BRANCH.tar.gz && mkdir -p .github &&  mv boost-ci-$BOOST_CI_BRANCH .github/boost-ci
          echo '==================================> PACKAGES'
          set -ex
          echo "Before package removal or install"
          whoami
          dpkg -l
          echo "Checking /usr/local"
          ls -al /usr/local
          echo "Checking clang"
          which clang++ || true
          clang++ --version || true
          ls -al /etc/alternatives
          ls -al /usr/bin/c*
          echo "about to run sudo apt-get purge -y $PACKAGES_TO_REMOVE"
          if [ -n "$PACKAGES_TO_REMOVE" ]; then sudo apt-get purge -y $PACKAGES_TO_REMOVE; fi
          echo "about to run linux-cxx-install.sh"
          ./.github/boost-ci/ci/drone/linux-cxx-install.sh
          echo "After package removal and install"
          dpkg -l
          echo "Checking /usr/local"
          ls -al /usr/local
          echo "Checking clang"
          which clang++ || true
          clang++ --version || true
          ls -al /etc/alternatives
          ls -al /usr/bin/c*
          echo '==================================> INSTALL AND COMPILE'
          . .github/scripts/6d5a3a255d-bbb3de2b00.sh
       
      - name: 6d5a3a255d-ed45733e6c
        #if: ${{ matrix.buildtype }} == 6d5a3a255d-ed45733e6c
        if: matrix.buildtype == '6d5a3a255d-ed45733e6c'
        shell: bash
        env:
          TRAVIS_BRANCH: ${{ github.base_ref }}
          CXX: ${{ matrix.cxx }}
          SOURCES: ${{ matrix.sources }}
          LLVM_OS: ${{ matrix.llvm_os }}
          LLVM_VER: ${{ matrix.llvm_ver }}
          PACKAGES: ${{ matrix.packages }}
          PACKAGES_TO_REMOVE: ${{ matrix.packages_to_remove }}
          TOOLSET: ${{ matrix.toolset }}
          CXXSTD: ${{ matrix.cxxstd }}
          DRONE_JOB_UUID: ${{ matrix.drone_job_uuid }}
          CXXFLAGS: ${{ matrix.cxxflags }}
          COMMENT: ${{ matrix.comment }}
          DEFINES: ${{ matrix.defines }}
          B2_VARIANT: ${{ matrix.b2_variant }}
          LINKFLAGS: ${{ matrix.linkflags }}
          UBSAN_OPTIONS: ${{ matrix.ubsan_options }}
          TESTFLAGS: ${{ matrix.testflags }}
          VALGRIND_OPTS: ${{ matrix.valgrind_opts }}
        run: |
          echo '==================================> SETUP'
          BOOST_CI_ORG=boostorg BOOST_CI_BRANCH=master && wget https://github.com/$BOOST_CI_ORG/boost-ci/archive/$BOOST_CI_BRANCH.tar.gz && tar -xvf $BOOST_CI_BRANCH.tar.gz && mkdir -p .github &&  mv boost-ci-$BOOST_CI_BRANCH .github/boost-ci
          echo '==================================> PACKAGES'
          set -ex
          echo "Before package removal or install"
          whoami
          dpkg -l
          echo "Checking /usr/local"
          ls -al /usr/local
          echo "Checking clang"
          which clang++ || true
          clang++ --version || true
          ls -al /etc/alternatives
          ls -al /usr/bin/c*
          echo "about to run sudo apt-get purge -y $PACKAGES_TO_REMOVE"
          if [ -n "$PACKAGES_TO_REMOVE" ]; then sudo apt-get purge -y $PACKAGES_TO_REMOVE; fi
          echo "about to run linux-cxx-install.sh"
          ./.github/boost-ci/ci/drone/linux-cxx-install.sh
          echo "After package removal and install"
          dpkg -l
          echo "Checking /usr/local"
          ls -al /usr/local
          echo "Checking clang"
          which clang++ || true
          clang++ --version || true
          ls -al /etc/alternatives
          ls -al /usr/bin/c*
          echo '==================================> INSTALL AND COMPILE'
          . .github/scripts/6d5a3a255d-ed45733e6c.sh
       
      - name: 6d5a3a255d-cce9827eb5
        #if: ${{ matrix.buildtype }} == 6d5a3a255d-cce9827eb5
        if: matrix.buildtype == '6d5a3a255d-cce9827eb5'
        shell: bash
        env:
          TRAVIS_BRANCH: ${{ github.base_ref }}
          CXX: ${{ matrix.cxx }}
          SOURCES: ${{ matrix.sources }}
          LLVM_OS: ${{ matrix.llvm_os }}
          LLVM_VER: ${{ matrix.llvm_ver }}
          PACKAGES: ${{ matrix.packages }}
          PACKAGES_TO_REMOVE: ${{ matrix.packages_to_remove }}
          TOOLSET: ${{ matrix.toolset }}
          CXXSTD: ${{ matrix.cxxstd }}
          DRONE_JOB_UUID: ${{ matrix.drone_job_uuid }}
          CXXFLAGS: ${{ matrix.cxxflags }}
          COMMENT: ${{ matrix.comment }}
          DEFINES: ${{ matrix.defines }}
          B2_VARIANT: ${{ matrix.b2_variant }}
          LINKFLAGS: ${{ matrix.linkflags }}
          UBSAN_OPTIONS: ${{ matrix.ubsan_options }}
          TESTFLAGS: ${{ matrix.testflags }}
          VALGRIND_OPTS: ${{ matrix.valgrind_opts }}
        run: |
          echo '==================================> SETUP'
          BOOST_CI_ORG=boostorg BOOST_CI_BRANCH=master && wget https://github.com/$BOOST_CI_ORG/boost-ci/archive/$BOOST_CI_BRANCH.tar.gz && tar -xvf $BOOST_CI_BRANCH.tar.gz && mkdir -p .github &&  mv boost-ci-$BOOST_CI_BRANCH .github/boost-ci
          echo '==================================> PACKAGES'
          set -ex
          echo "Before package removal or install"
          whoami
          dpkg -l
          echo "Checking /usr/local"
          ls -al /usr/local
          echo "Checking clang"
          which clang++ || true
          clang++ --version || true
          ls -al /etc/alternatives
          ls -al /usr/bin/c*
          echo "about to run sudo apt-get purge -y $PACKAGES_TO_REMOVE"
          if [ -n "$PACKAGES_TO_REMOVE" ]; then sudo apt-get purge -y $PACKAGES_TO_REMOVE; fi
          echo "about to run linux-cxx-install.sh"
          ./.github/boost-ci/ci/drone/linux-cxx-install.sh
          echo "After package removal and install"
          dpkg -l
          echo "Checking /usr/local"
          ls -al /usr/local
          echo "Checking clang"
          which clang++ || true
          clang++ --version || true
          ls -al /etc/alternatives
          ls -al /usr/bin/c*
          echo '==================================> INSTALL AND COMPILE'
          . .github/scripts/6d5a3a255d-cce9827eb5.sh
       

